---
title: "grocery_processed"
author: "Christine Brown"
date: "April 19, 2017"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,  warning = F , message = F)
```
Set-Up
```{r}
#Load Packages
library( dplyr )
library( geojsonio )
library( ggmap )
library( maps )
library( maptools )
library( raster )
library( rgdal )
library( rgeos )
library( sp )
library( tools )

#Prepare Working Directory
setwd("C:/Users/brown/Documents/Grad School/Fall 16/DDMII/SyracuseLandBank/DATA/PROCESSED_DATA")

```


```{r}

#Load Data
grocery <- read.csv("https://raw.githubusercontent.com/christine-brown/SyracuseLandBank/master/DATA/RAW_DATA/grocery_raw.csv", stringsAsFactors=FALSE)
syr_tracts <- geojson_read("https://raw.githubusercontent.com/christine-brown/SyracuseLandBank/master/SHAPEFILES/SYRCensusTracts.geojson", method="local", what="sp")
syr_tracts <- spTransform(syr_tracts, CRSobj=CRS("+proj=longlat +datum=WGS84"))

#Clean Data
grocery$City <- ifelse(is.na(grocery$City), grocery$ARC_City_1, grocery$City)
grocery <- mutate( grocery, Address=paste( Location,City,"NY",ZipCode, sep=", "))
grocery <- grocery[, c("Supermarke", "Address")]

#Geocode
grocery_coordinates <- suppressMessages(geocode( grocery$Address, messaging=F ))
grocery <- cbind(grocery, grocery_coordinates)

#Match to Census Tract
grocery_coordinates_SP <- SpatialPoints(grocery_coordinates, proj4string=CRS("+proj=longlat +datum=WGS84") )
grocery_tracts <- over(grocery_coordinates_SP, syr_tracts ) # note that this will only provide information for stores in Syracuse census tracts, so many of the stores will have NA as values
grocery <- cbind( grocery, grocery_tracts )
grocery <- filter(grocery, !is.na(INTPTLON10) )

#Export to CSV
write.csv(grocery, file = "grocery_processed.csv", row.names=FALSE)

```